### PR TITLE
Code cleanup, updates, and typo fixes

### PR DESCRIPTION
**Pull request by TacoTheDank**
Now, don't panic at the number of files changed. Everything will be explained :)

### 1st commit
- Adds a gradle validation action (see more [here](https://github.com/ccrama/Slide/pull/3221))

### 2nd commit
- Updates the gradle wrapper to 6.5.1 using git bash

### 3rd commit
- Specifies usage of buildTools 29.0.3 (otherwise it uses an outdated version)
- Adds an applicationIdSuffix to the debug builds
- Organize and group libraries (and remove unneeded ones)

### 4th commit
- Adjusts codestyle to an .editorconfig (done automatically by Android Studio)

### 5th commit
- Cleans up and optimizes some miscellaneous code

### 6th commit
- Fixes the two vibration deprecations (I think), you can read about it [here](https://developer.android.com/reference/android/os/Vibrator#vibrate(long))

### 7th commit
- Updates Coroutines 1.3.4 -> 1.3.8 ([changelog](https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md))
- Updates Material 1.2.0-beta01 -> 1.2.0-rc01 ([changelog](https://github.com/material-components/material-components-android/releases/tag/1.2.0-rc01))

### 8th commit
- Reduce APK size by excluding useless META-INF (if I'm right, it should shrink by around 200KB)

### 9th commit
- Fixes grammar in the .md files (and metadata's full_description)
- Updates badges
- Cleans up markdown for easier reading

<br/>
Hope you agree with all this. Thanks for this awesome app!

### CODE REVIEW

**Comment by TacoTheDank** [comment]
EDIT: It seems there's a possible issue with Coroutines 1.3.7 onward https://github.com/Kotlin/kotlinx.coroutines/issues/2049. If this issue appears in the app, we'll have to revert Coroutines to 1.3.6.

**Comment by y20k** [comment]
Thank you!

**Comment by y20k** [comment]
I inspected the changes proposed in this pull request. Most of the code style changes I had to revert. I am just too used to the style I am using in my projects. :-) 

If this was a real community project with many contributes I understand that I would need to compromise on that front. But at the moment I am the only developer here.

**Comment by TacoTheDank** [comment]
Alright, sound good. Thanks!

**Comment by TacoTheDank** [comment]
It seems you've also reverted the code cleanup and deprecation fixes with the code style revert. Seeing as how the related commits in the request came after the codestyle one, I'm just wondering if that was intentional.

**Pull request merged**
