### PR TITLE
Library updates, KTX extensions, and code cleanup

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update Kotlin Coroutines 1.3.8 -> 1.3.9 ([changelog](https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md))
- Update AndroidX ConstraintLayout 2.0.2 -> 2.0.4 ([changelog](https://developer.android.com/jetpack/androidx/releases/constraintlayout))
- Update Google Material 1.2.0-rc01 -> 1.2.1 ([changelog](https://github.com/material-components/material-components-android/releases))
- Update AndroidX Navigation 2.3.0 -> 2.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/navigation))

### 2nd commit
- Use several KTX features to Kotlin-ize and simplify code

### 3rd commit
- Miscellaneous code cleanup

If there's anything you don't like or would like me to change, tell me so I can fix it (so you don't have to revert stuff you don't want after merging ;)).

### CODE REVIEW

**Comment by y20k** [comment]
Hi @TacoTheDank 

Thanks for the pull request. I need to have a closer look. Give my a couple of days.

Sometimes choices in code style in this project are made because I find the result better readable. Since I am the maintainer and more or less exclusive contributor of code, I need to factor my personal preference in :-). At a first glace I like the choices you made.

Just because I am curious. How are you working? Did you do all the code improvements by yourself, or do you make use of Android Studio suggestions?

**Comment by TacoTheDank** [comment]
@y20k Some of them were Android Studio suggestions, others I made myself.

**Comment by y20k** [comment]
Today I found the time to look through the proposed changes. Some of them are great. Thanks :heart:. But some changes make the resulting code slightly less readable for me personally. 

The easiest way to review your pull request was to go through it line by line. It was a bit of work, but it was worth it. 

What I made of your pull request, can be seen here: [eb29618](https://github.com/y20k/trackbook/commit/eb296188d80a1e0f852a8c2eff2028a48f4cc93b)

I now need to close this pul request. Sorry for the unconventional handling of it. It was as I wrote easier for me this way.

**Comment by TacoTheDank** [comment]
@y20k That's alright. Thanks!

**Pull request closed without merging**
