### PR TITLE
Add yes/no prompt before clearing active track.

### PR DESCRIPTION
**Pull request by voussoir**
Screenshot_20220404-151536

### CODE REVIEW

**Comment by Hob111** [comment]
I'd support this idea. I did once delete a track accidentally, not a frequent occurrence but annoying when it happens. :angry:

**Comment by voussoir** [comment]
My personal preference is to prompt before clearing. I don't really enjoy those pop-up undo buttons because first my brain needs to realize I made a mistake, then I need to click it before it disappears, and this makes me feel a sense of panic. I also feel sympathy for people learning the language who need more time to read.

Trackbook is used outdoors where the sunlight makes it hard to see properly in the first place.

Could we do both? Prompt first and offer an undo button for the very clumsy people who ok the prompt by accident too? If so, we could implement the same thing for track deleting too.

**Comment by y20k** [comment]
Good point(s).

**Comment by Hob111** [comment]
The new screen layout #115 will make accidental deletion less likely **but** better safe than sorry. After some thought I too think that the dialogue is better. 
@voussoir suggests doing this for track deletion too. An excellent idea, I've always been wary (and fearful!) of _Delete Non-Starred Recordings_ in Settings.

**Pull request merged**
